version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev && npm run dev"
    depends_on:
      postgres-dev:
        condition: service_healthy

  postgres-dev:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB="dev"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-dev-data: