name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "Environment variable DATABASE_URL is set."

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build

      # Run lint checks
      - name: Run lint checks
        run: npm run lint
